sudo: required

language: node_js
  -6

services:
  - docker

before_install:
  - docker pull selenium/standalone-chrome
  - docker run -d -p 127.0.0.1:4444:4444 selenium/standalone-chrome
  - docker ps
install:
  - npm install

script:
  - npm test