sudo: required

language: node_js
  -6

services:
  - docker

before_install:
  - docker pull selenium/standalone-chrome
  - docker run -d -P selenium/standalone-chrome
  - docker ps
install:
  - npm install

script:
  - npm test