##seleniumhub:
##  image: selenium/hub:2.53.0
##  ports:
##    - 4444:4444
##
##chromenode:
##  image: selenium/node-chrome:2.53.0
##  ports:
##    - 5900
##  links:
##    - seleniumhub:hub
#
#selenium:
#  container_name: selenium
#  image: selenium/standalone-chrome-debug:3.1.0-astatine
#  shm_size: 1g
#  ports:
#    - 4444:4444
#    - 5900:5900
#  volumes:
#    - ${PWD}/edit/test/protractor/files:/edit/files
#    - ${PWD}/edit/test/protractor/images:/edit/images
#    - ${PWD}/poller/images:/poller/images
#    - /dev/shm:/dev/shm
version: '2'
services:
  rover:
    container_name: rover
    build: rover
    image: quay.io/hearst/rover:master
    ports:
      - 80
    volumes:
      - ${PWD}/rover:/app
      - ${PWD}/fixtures:/app/fixtures
    volumes_from:
      - rover-data
    depends_on:
      - rover-postgres
      - rover-redis
    environment:
      - VIRTUAL_HOST=rover.docker
      - PYTHONDONTWRITEBYTECODE=true      # no pyc files
      - NEW_RELIC_MONITOR_MODE=false
      - NEW_RELIC_LOG=/dev/null

  rover-data:
    container_name: rover-data
    build: rover
    image: quay.io/hearst/rover:master
    command: ls
    volumes:
      - /app/static
    environment:
      - PYTHONDONTWRITEBYTECODE=true      # no pyc files

  rover-postgres:
    container_name: rover-postgres
    image: quay.io/hearst/rover-postgres:master
    environment:
      - VIRTUAL_HOST=rover-postgres.docker
      - POSTGRES_PASSWORD=password
    ports:
      - 15432:5432

  rover-redis:
    container_name: rover-redis
    image: redis

  rover-admin-ui:
    container_name: rover-admin-ui
    build:
      context: rover-admin-ui
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    image: quay.io/hearst/rover-admin-ui:master
    volumes:
      - ${PWD}/rover-admin-ui:/app
    ports:
      - 3000
    depends_on:
      - rover
      - rover-admin-ui-redis
    environment:
      - APP_SETTINGS=settings
      - AUTH_BASE_URI=http://rover.docker
      - DEBUG=true
      - DOORMAN_URL=http://rover.docker/
      - ENV=development
      - HEALTHCHECK_TOKEN=12345
      - PYTHONDONTWRITEBYTECODE=true
      - REDIS_HOST=rover-admin-ui-redis
      - REDIS_PORT=6379
      - ROVER_BASE_URL=http://rover.docker/v2
      - ROVER_CLIENT_ID=key
      - ROVER_CLIENT_SECRET=secret
      - ROVER_RESET_PASSWORD_URL=http://rover.docker/admin/recover/
      - ROVERUIADMIN_SECRET=notsosecret
      - SENTRY_DSN=
      - SENTRY_PUBLIC_DSN=
      - VIRTUAL_HOST=rover-admin-ui.docker

  rover-admin-ui-redis:
    container_name: rover-admin-ui-redis
    image: redis

  nitehawk:
    container_name: nitehawk
    build: nitehawk
    image: quay.io/hearst/nitehawk
    volumes:
      - ${PWD}/nitehawk:/app
    ports:
      - 80
    depends_on:
      - rover
    environment:
      - VIRTUAL_HOST=nitehawk.docker
      - PYTHONDONTWRITEBYTECODE=true     # no pyc files
      - ROVER_BASE_URL=http://rover/v2/
      - ROVER_CLIENT_ID=key
      - ROVER_CLIENT_SECRET=secret

  kubrick:
    container_name: kubrick
    build: kubrick
    image: quay.io/hearst/kubrick
    volumes:
      - ${PWD}/kubrick:/app
    ports:
      - 80
    environment:
      - VIRTUAL_HOST=kubrick.docker

  hives:
    container_name: hives
    build: kubrick
    image: quay.io/hearst/kubrick
    volumes:
      - ${PWD}/kubrick:/app
    ports:
      - 80
    environment:
      - VIRTUAL_HOST=hives.docker
      - VIDEO_DISABLED=1

  edit:
    container_name: edit
    build:
      context: edit
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    image: quay.io/hearst/edit
    ports:
      - 80
    volumes:
      - ${PWD}/edit:/var/www
    depends_on:
      - dispatchr
      - diversion
      - edit-redis
      - hips
      - master-record
      - nitehawk
      - rover
      - tran
      - tyrion
      - seekr
      - germinator
    environment:
      - CONTENT_TESTING_BABOU_URL=http://babou.hdmtech.net
      - CONTENT_TESTING_KRIEGER_URL=http://krieger-dev.hdmtech.net
      - DATAMART_URLS=https://dev-buzzing.hearst.io
      - DATAMART_VERSION=v1
      - DISPATCHR_URLS=http://dispatchr
      - DIVERSION_CACHE_PREFIX=diversion
      - DIVERSION_URLS=http://diversion
      - MASTER_RECORD_URLS=http://master-record
      - DOORMAN_URL=http://rover.docker/admin
      - ENSIGHTEN_ENABLED=1
      - ESEARCH_URLS=http://seekr
      - ESEARCH_INDEX_NAME=${CURRENT_SITE}-${CURRENT_LOCALE_LANGUAGE}-${CURRENT_LOCALE_COUNTRY_CODE}
      - HEALTHCHECK_TOKEN=edit-compose
      - HOSTNAME_OVERRIDE=fre.docker
      - KUBRICK_URLS = kubrick.docker
      - PUBLIC_IMAGE_HOSTNAME=http://hips.docker/hdm-dev
      - REDIS_HOSTNAME=edit-redis
      - ROVER_URLS=http://rover
      - ROVER_API_KEY=key
      - ROVER_API_SECRET=secret
      - ROVER_API_REDIRECT_URL=http://localhost/doesnt/matter
      - SEED=false
      - SELENIUM_ADDRESS=http://selenium.docker:4444/wd/hub
      - TRAN_URLS=http://tran
      - TYRION_URLS=http://tyrion
      - VIRTUAL_HOST=edit.docker,*.edit.docker

  edit-redis:
    container_name: edit-redis
    image: redis
    ports:
      - 63791:6379

  fre-theme-shared:
    container_name: fre-theme-shared
    build:
      context: fre
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    image: quay.io/hearst/fre-theme-shared
    ports:
      - 80
    volumes:
      - ${PWD}/fre:/var/www
    depends_on:
      - diversion
      - fre-redis
      - hips
      - master-record
      - rover
      - tyrion
      - seekr
    environment:
      - BABOU_URLS=http://babou.hdmtools.com/api
      - BABOU_VERSION=v2
      - CURRENT_SITE=${CURRENT_SITE}
      - CURRENT_BRAND_NAME=${CURRENT_BRAND_TITLE}
      - DATAMART_URLS=https://dev-buzzing.hearst.io
      - DATAMART_VERSION=v1
      - DIVERSION_URLS=http://diversion
      - DOORMAN_URLS=http://rover
      - DOORMAN_VERSION=v2
      - DOORMAN_API_REDIRECT_URL=http://fre-theme-shared.docker
      - ENSIGHTEN_ENABLED=1
      - ESEARCH_URLS=http://seekr
      - ESEARCH_INDEX_NAME=${CURRENT_SITE}-${CURRENT_LOCALE_LANGUAGE}-${CURRENT_LOCALE_COUNTRY_CODE}
      - HEALTHCHECK_TOKEN=fre-compose
      - CONTENT_TESTING_KRIEGER_SECRET=87654321
      - CONTENT_TESTING_KRIEGER_URL=http://krieger-dev.hdmtech.net
      - CONTENT_TESTING_KRIEGER_VERSION=v2
      - MASTER_RECORD_URLS=http://master-record
      - SLIDE_AD_FREQUENCY=5
      - PUBLIC_IMAGE_HOSTNAME=http://hips.docker/hdm-dev
      - REDIS_HOSTNAME=fre-redis
      - ROVER_API_KEY=12345678
      - ROVER_API_REDIRECT_URL=http://fre-theme-shared.docker
      - ROVER_API_SECRET=87654321
      - ROVER_URLS=http://rover
      - SELENIUM_ADDRESS=http://selenium.docker:4444/wd/hub
      - SHARE_COUNTS_URLS=https://hds-api.hearst.io/dev
      - THEME=hdm
      - THEME_LOCATION=themes/hdm
      - TYRION_URLS=http://tyrion
      - VIRTUAL_HOST=fre-theme-shared.docker,fre.docker

  fre-hdm:
    container_name: fre-hdm
    build:
      context: fre-hdm
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    image: quay.io/hearst/fre-theme-hdm
    ports:
      - 80
    volumes:
      - ${PWD}/fre-hdm:/var/www
    depends_on:
      - diversion
      - fre-redis
      - hips
      - master-record
      - rover
      - tyrion
      - seekr
    environment:
      - AMP_ELIGIBILITY=1
      - API_URLS=http://rover
      - ASSET_HOSTNAME=https://assets.hearstapps.net
      - BABOU_URLS=http://babou.hdmtools.com/api
      - BABOU_VERSION=v2
      - DATAMART_URLS=https://dev-buzzing.hearst.io
      - DATAMART_VERSION=v1
      - DIVERSION_URLS=http://diversion
      - DOORMAN_API_REDIRECT_URL=http://fre-hdm.docker
      - DOORMAN_URLS=http://rover
      - DOORMAN_VERSION=v2
      - ENSIGHTEN_ENABLED=1
      - EMBED_ICON_FONT=true
      - ESEARCH_URLS=http://seekr
      - HOMEPAGE_ITEMS_CACHE_KEY=homepage-items
      - LAZYLOAD_EMBEDS=true
      - LIST_AD_FREQUENCY=3
      - MASTER_RECORD_URLS=http://master-record
      - PUBLIC_IMAGE_HOSTNAME=http://hips.docker/hips/hdm-dev
      - REDIS_HOSTNAME=fre-redis
      - ROVER_API_REDIRECT_URL=http://fre-hdm.docker
      - ROVER_API_KEY=12345678
      - ROVER_API_SECRET=87654321
      - ROVER_URLS=http://rover
      - SELENIUM_ADDRESS=http://selenium.docker:4444/wd/hub
      - SHARE_COUNTS_URLS=https://hds-api.hearst.io/dev
      - SHOULD_USE_LEGACY_ID_BOUNDARY=0
      - SLIDE_AD_FREQUENCY=5
      - TYRION_URLS=http://tyrion
      - VIRTUAL_HOST=${CURRENT_SITE}.docker,fre-theme-hdm.docker,*.fre-theme-hdm.docker,fre-hdm.docker,*.fre-hdm.docker
      - YII_ENVIRONMENT=dev

  fre-htv:
    container_name: fre-htv
    build: fre/themes/htv
    image: quay.io/hearst/fre-theme-htv
    ports:
      - 80
    volumes:
      - ${PWD}/fre/themes/htv:/var/www/themes/htv
    volumes_from:
      - fre-htv-data
    depends_on:
      - fre-redis
      - rover
      - diversion
    environment:
      - THEME=htv
      - THEME_LOCATION=themes/htv
      - CURRENT_SITE=ksbw
      - CURRENT_BRAND_NAME=KSBW
      - PUBLIC_IMAGE_HOSTNAME=http://hips.docker/hips/hdm-dev
      - REDIS_HOSTNAME=fre-redis
      - ROVER_URLS=http://rover
      - API_URLS=http://rover
      - DATAMART_URLS=https://dev-buzzing.hearst.io
      - DATAMART_VERSION=v1
      - DOORMAN_URLS=http://rover
      - DOORMAN_VERSION=v2
      - ROVER_API_REDIRECT_URL=http://ksbw.docker
      - ROVER_API_KEY=12345678
      - ROVER_API_SECRET=87654321
      - VIRTUAL_HOST=ksbw.docker
      - DIVERSION_URLS=http://diversion

  fre-htv-data:
    container_name: fre-htv-data
    build: fre/themes/htv
    image: quay.io/hearst/fre-theme-htv
    command: ls
    volumes:
      - /var/www/themes/htv/assets
      - /var/www/themes/htv/vendor
      - /var/www/themes/htv/node_modules
      - /var/www/themes/htv/sites/${CURRENT_SITE}/assets

  fre-redis:
    container_name: fre-redis
    image: redis
    ports:
      - 63792:6379

  hips:
    container_name: hips
    build: hips
    image: quay.io/hearst/hips
    ports:
      - 6116
    environment:
      - VIRTUAL_HOST=hips.docker
      - HIPS_THROTTLE=1
      - HIPS_CONCURRENCY=10
      - HIPS_BURST=200
      - HIPS_LOG_LEVEL=development
      - HEALTHCHECK_TOKEN=hips-compose

  tyrion:
    container_name: tyrion
    build:
      context: tyrion
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    image: quay.io/hearst/tyrion
    ports:
      - 80
    volumes:
      - ${PWD}/tyrion:/var/www
    volumes_from:
      - tyrion-data
    environment:
      - TYRION_APP_HEALTHCHECK_TOKEN=tyrion-compose
      - TYRION_APP_HOSTNAME=http://tyrion.docker
      - VIRTUAL_HOST=tyrion.docker

  tyrion-data:
    container_name: tyrion-data
    build:
      context: tyrion
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    image: quay.io/hearst/tyrion
    command: ls
    volumes:
      - /var/www/node_modules

  dispatchr:
    container_name: dispatchr
    build: dispatchr
    image: quay.io/hearst/dispatchr
    ports:
      - 80
    volumes:
      - ${PWD}/dispatchr:/var/www
    volumes_from:
      - dispatchr-data
    environment:
      - DISPATCHR_APP_HEALTHCHECK_TOKEN=dispatchr-compose
      - DISPATCHR_APP_HOSTNAME=http://dispatchr.docker
      - VIRTUAL_HOST=dispatchr.docker

  dispatchr-data:
    container_name: dispatchr-data
    build: dispatchr
    image: quay.io/hearst/dispatchr
    command: ls
    volumes:
      - /var/www/node_modules

  poller:
    container_name: poller
    build:
      context: poller
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    env_file:
      - poller/.env
    depends_on:
      - dispatchr
    image: quay.io/hearst/poller
    ports:
      - 80
    volumes:
      - ${PWD}/poller:/var/www
    environment:
      - VIRTUAL_HOST=poller.docker

  diversion-postgres:
    container_name: diversion-postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password

  diversion-redis:
    container_name: diversion-redis
    image: redis

  diversion:
    container_name: diversion
    build:
      context: diversion
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    image: quay.io/hearst/diversion
    ports:
      - 80
    volumes:
      - ${PWD}/diversion:/app
    volumes_from:
      - diversion-data
    depends_on:
      - diversion-postgres
      - diversion-redis
      - rover
    environment:
      - AUTHENTICATION_URLS=http://rover
      - CACHE_PREFIX=diversion
      - DEFAULT_CACHE_RESPONSE_TIMEOUT=1
      - FEATURE_AUTH_PERMISSIONS_ON=True        #(TRUE|FALSE)
      - HEALTHCHECK_TOKEN=diversion-compose
      - LOG_LEVEL=INFO                          #(ERROR|WARNING|INFO|DEBUG)
      - PYTHONDONTWRITEBYTECODE=true            # no pyc files
      - VIRTUAL_HOST=diversion.docker
      - ROVER_BASE_URL=http://rover.docker/v2
      - ROVER_CLIENT_ID=key
      - ROVER_CLIENT_SECRET=secret

  diversion-data:
    container_name: diversion-data
    build:
      context: diversion
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    image: quay.io/hearst/diversion
    command: ls
    volumes:
      - /app/static

  master-record-postgres:
    container_name: master-record-postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password

  master-record-redis:
    container_name: master-record-redis
    image: redis

  master-record:
    container_name: master-record
    build:
      context: master-record
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    image: quay.io/hearst/master-record
    ports:
      - 80
    volumes:
      - ${PWD}/master-record:/app
    volumes_from:
      - master-record-data
    depends_on:
      - master-record-postgres
      - master-record-redis
      - rover
    environment:
      - AUTHENTICATION_URLS=http://rover
      - FEATURE_AUTH_PERMISSIONS_ON=True        #(TRUE|FALSE)
      - HEALTHCHECK_TOKEN=master-record-compose
      - LOG_LEVEL=INFO                          #(ERROR|WARNING|INFO|DEBUG)
      - PYTHONDONTWRITEBYTECODE=true            # no pyc files
      - VIRTUAL_HOST=master-record.docker

  master-record-data:
    container_name: master-record-data
    build:
      context: master-record
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    image: quay.io/hearst/master-record
    command: ls
    volumes:
      - /app/static

  feed-the-beast-postgres:
    container_name: beast-postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password

  feed-the-beast:
    container_name: feed-the-beast
    build:
      context: feed-the-beast
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    image: quay.io/hearst/beast
    ports:
      - 80
    volumes:
      - ${PWD}/feed-the-beast:/go/src/github.com/Hearst-Hatchery/feed-the-beast
    depends_on:
      - feed-the-beast-postgres
      - tran
      - diversion
      - rover
    environment:
      - TRAN_URL=http://tran
      - ROVER_URL=http://rover
      - EDIT_DOMAIN=edit.docker
      - ROVER_API_VERSION=2
      - DIVERSION_URL=http://diversion
      - AUTH_REQUIRED=true
      - VIRTUAL_HOST=feed-the-beast.docker

  tran-postgres:
    container_name: tran-db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password

  tran-redis:
    container_name: tran-redis
    image: redis

  tran:
    container_name: tran
    build: tran
    image: quay.io/hearst/tran
    ports:
      - 80
    volumes:
      - ${PWD}/tran:/app
    volumes_from:
      - tran-data
    depends_on:
      - tran-postgres
      - tran-redis
      - rover
      - master-record
    env_file:
      - tran/env/.env
    environment:
      - ROVER_HOST=http://rover
      - DOORMAN_HOST=http://rover
      - VIRTUAL_HOST=tran.docker
      - CACHE_HOST=redis://tran-redis/1
      - MASTER_RECORD_HOST=http://master-record
      - HEALTHCHECK_TOKEN=tran-compose
      - DEBUG=True
      - USE_AUTH=True
      - TRAN_ENVIRONMENT=dev
      - TRAN_URL=http://tran.docker

  tran-data:
    container_name: tran-data
    build: tran
    image: quay.io/hearst/tran
    command: ls
    volumes:
      - /app/docs
      - /app/staticfiles

  seekr:
    container_name: seekr
    build:
      context: seekr
      args:
        - GITHUB_TOKEN
    image: quay.io/hearst/seekr
    ports:
      - 8081:8081
    volumes:
      - ${PWD}/seekr:/go/src/github.com/Hearst-Hatchery/seekr
    depends_on:
      - seekr-elasticsearch
      - rover
    environment:
      - SEEKR_ROVER_URL=http://rover
      - SEEKR_ELASTICSEARCH_URL=http://seekr-elasticsearch:9200
      - SEEKR_API_HOST=0.0.0.0
      - VIRTUAL_HOST=seekr.docker
      - SEEKR_MESSAGES_THROTTLE=2000
      - HEALTHCHECK_TOKEN=seekr-compose

  seekr-elasticsearch:
    container_name: seekr-elasticsearch
    image: elasticsearch:1.7.5
    ports:
      - 9200:9200
    command: elasticsearch --index.number_of_shards=1

  aeon:
    container_name: aeon
    build: aeon
    image: quay.io/hearst/aeon
    ports:
      - 8080
    depends_on:
      - aeon-redis
      - edit-redis
      - dispatchr
      - fre-redis
      - rover
    volumes:
      - ${PWD}/aeon:/go/src/github.com/Hearst-Hatchery/aeon
    environment:
      - AEON_CACHE_INVALIDATION_REDIS_HOSTNAMES=edit-redis:6379,fre-redis:6379
      - AEON_CACHE_INVALIDATION_REDIS_PREFIXES=mp-edit,mp-fre
      - AEON_DISPATCHR_HOSTNAME=http://dispatchr
      - AEON_REDIS_ADDRESS=aeon-redis:6379
      - AEON_ROVER_HOSTNAME=http://rover
      - VIRTUAL_HOST=aeon.docker
      - HEALTHCHECK_TOKEN=aeon-compose

  aeon-redis:
    container_name: aeon-redis
    image: redis

  germinator-postgres:
    container_name: germinator-postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password

  germinator:
    container_name: germinator
    build:
      context: teh-germinator
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    image: quay.io/hearst/teh-germinator
    ports:
      - 80
    volumes:
      - ${PWD}/teh-germinator:/var/www
      - /var/www/vendor
    depends_on:
      - rover
      - diversion
      - germinator-postgres
    environment:
      - VIRTUAL_HOST=germinator.docker
      - DIVERSION_HOST=http://diversion
      - GERMINATOR_ROVER_HOST=http://rover
      - DB_CONNECTION=pgsql
      - DB_HOST=germinator-postgres
      - DB_NAME=postgres
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - QUEUE_DRIVER=database
      - CACHE_DRIVER=array
      - SESSION_DRIVER=array
      - QUEUE_TABLE=jobs
      - QUEUE_TIMEOUT=0
      - QUEUE_RETRIES=3
      - QUEUE_FAILED_TABLE=failed_jobs
      - APP_DEBUG=true
      - SEED=True
      - SEED_BRAND=${CURRENT_BRAND_TITLE}
      - SEED_LOCALE_URL_PATH=${CURRENT_LOCALE_URL_PATH}
      - SEEDEVERYTHING=False

  partnerfeed-db-dummy:
    image: rwgrim/docker-noop

  partnerfeed-dummy:
    image: rwgrim/docker-noop

  howdy-postgres-dummy:
    image: rwgrim/docker-noop

  howdy-dummy:
    image: rwgrim/docker-noop

  video-player:
    container_name: video-player
    build: video-player
    image: quay.io/hearst/video-player:latest
    ports:
      - 8000
    volumes:
      - ${PWD}/video-player:/app
    depends_on:
      - rover
      - nitehawk
    environment:
      - VIRTUAL_HOST=player.docker
      - ENV=docker

  selenium:
    container_name: selenium
    image: selenium/standalone-chrome-debug:3.1.0-astatine
    shm_size: 1g
    ports:
      - 4444:4444
      - 5900:5900
    volumes:
      - ${PWD}/edit/test/protractor/files:/edit/files
      - ${PWD}/edit/test/protractor/images:/edit/images
      - ${PWD}/poller/images:/poller/images
      - /dev/shm:/dev/shm

  doody-dummy:
    image: rwgrim/docker-noop

  feather-dummy:
    image: rwgrim/docker-noop
